#! /bin/sh
#  /etc/init.d/dnsDaemon

### BEGIN INIT INFO
# Provides:          DnsDaemon
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Short-Description: Starts the DnsDaemon service
# Description:       This file is used to start the daemon
#                    and should be placed in /etc/init.d
### END INIT INFO

# Author:   Dimitris Dedousis <dimitris.dedousis@gmail.com>
# Date:     19/04/2014

NAME="dnsDaemon"
DESC="DnsDaemon service"
# The path to Jsvc
EXEC="/usr/bin/jsvc"
# The path to the folder containing dnsdaemon.jar
FILE_PATH="/etc/dnsUpdater"
# Our classpath including our jar file and the Apache Commons Daemon library
CLASS_PATH="$FILE_PATH/dnsUpdater-1.0-SNAPSHOT-jar-with-dependencies.jar"
# The fully qualified name of the class to execute
CLASS="gr.aueb.daemon.DnsDaemon"

#The user to run the daemon as
USER="root"

# The file that will contain our process identification number (pid) for other scripts/programs that need to access it.
PID="/var/run/$NAME.pid"

# System.out writes to this file...
LOG_OUT="$FILE_PATH/log/$NAME.out"

# System.err writes to this file...
LOG_ERR="$FILE_PATH/log/$NAME.err"


jsvc_exec()
{
    cd $FILE_PATH
    $EXEC -home $JAVA_HOME -cp $CLASS_PATH -user $USER -outfile $LOG_OUT -errfile $LOG_ERR -pidfile $PID $1 $CLASS
}

case "$1" in
    start)
        echo "Starting the $DESC..."

        # Start the service
        jsvc_exec

        echo "The $DESC has started."
    ;;
    status)
        if [ -f "$PID" ]; then
            echo "$DESC is running."
        else
            echo "$DESC is not running."
        fi
    ;;
    stop)
        echo "Stopping the $DESC..."

        # Stop the service
        jsvc_exec "-stop"

        echo "The $DESC has stopped."
    ;;
    restart)
        if [ -f "$PID" ]; then

            echo "Restarting the $DESC..."

            # Stop the service
            jsvc_exec "-stop"

            # Start the service
            jsvc_exec

            echo "The $DESC has restarted."
        else
            echo "Daemon not running, no action taken"
            exit 1
        fi
            ;;
    *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|status}" >&2
    exit 3
    ;;
esac
